// Projects
export const FETCH_PROJECTS = 'FETCH_PROJECTS'
export const CREATE_PROJECT = 'CREATE_PROJECT'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const SET_ACTIVE_PROJECT = 'SET_ACTIVE_PROJECT'

// Sprints
export const SET_SPRINTS = 'SET_SPRINTS'
export const CREATE_SPRINT = 'CREATE_SPRINT'
export const UPDATE_SPRINT = 'UPDATE_SPRINT'
export const DELETE_SPRINT = 'DELETE_SPRINT'
export const ROLLBACK_SPRINT = 'ROLLBACK_SPRINT'
export const UNSET_SPRINTS = 'UNSET_SPRINTS'

// Backlogs
export const SET_BACKLOG = 'SET_BACKLOG'
export const UNSET_BACKLOG = 'UNSET_BACKLOG'

// Todos
export const SET_TODOS = 'SET_TODOS'

// Issues
export const SET_SPRINT_ISSUES = 'SET_SPRINT_ISSUES'
export const SET_BACKLOG_ISSUES = 'SET_BACKLOG_ISSUES'
export const CREATE_SPRINT_ISSUE = 'CREATE_SPRINT_ISSUE'
export const CREATE_BACKLOG_ISSUE = 'CREATE_BACKLOG_ISSUE'
export const UPDATE_SPRINT_ISSUE = 'UPDATE_SPRINT_ISSUE'
export const UPDATE_BACKLOG_ISSUE = 'UPDATE_BACKLOG_ISSUE'
export const DELETE_SPRINT_ISSUE = 'DELETE_ISSUE'
export const DELETE_BACKLOG_ISSUE = 'DELETE_ISSUE'
export const ROLLBACK_SPRINT_ISSUE = 'ROLLBACK_SPRINT_ISSUE'
export const ROLLBACK_BACKLOG_ISSUE = 'ROLLBACK_BACKLOG_ISSUE'

// Actions
export const SET_DRAGGED = 'SET_DRAGGED'
export const UNSET_DRAGGED = 'UNSET_DRAGGED'
export const SET_FETCH_LOADING = 'SET_FETCH_LOADING'
export const UNSET_FETCH_LOADING = 'UNSET_FETCH_LOADING'
export const SET_ACTION_LOADING = 'SET_ACTION_LOADING'
export const UNSET_ACTION_LOADING = 'UNSET_LOADING_ACTION'

// Users
export const SET_USER = 'SET_USER'