// Projects
export const FETCH_PROJECTS = 'FETCH_PROJECTS'
export const CREATE_PROJECT = 'CREATE_PROJECT'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const SET_ACTIVE_PROJECT = 'SET_ACTIVE_PROJECT'
export const SET_BACKLOG = 'SET_BACKLOG'

// Sprints
export const SET_SPRINTS = 'SET_SPRINTS'

// Todos
export const SET_TODOS = 'SET_TODOS'

// Issues
export const SET_SPRINT_ISSUES = 'SET_SPRINT_ISSUES'
export const SET_BACKLOG_ISSUES = 'SET_BACKLOG_ISSUES'
export const CREATE_SPRINT_ISSUE = 'CREATE_SPRINT_ISSUE'
export const CREATE_BACKLOG_ISSUE = 'CREATE_BACKLOG_ISSUE'
export const UPDATE_SPRINT_ISSUE = 'UPDATE_SPRINT_ISSUE'
export const UPDATE_BACKLOG_ISSUE = 'UPDATE_BACKLOG_ISSUE'
export const DELETE_SPRINT_ISSUE = 'DELETE_ISSUE'
export const DELETE_BACKLOG_ISSUE = 'DELETE_ISSUE'
export const ROLLBACK_SPRINT_ISSUE = 'ROLLBACK_SPRINT_ISSUE'
export const ROLLBACK_BACKLOG_ISSUE = 'ROLLBACK_BACKLOG_ISSUE'

// Actions
export const SET_DRAGGED = 'SET_DRAGGED'
export const UNSET_DRAGGED = 'UNSET_DRAGGED'
export const SET_FETCHING = 'SET_FETCHING'
export const UNSET_FETCHING = 'UNSET_FETCHING'